version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"

- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "main"
  ignore:
    - dependency-name: "symfony/console"
      versions: [ "6.x" ]
    - dependency-name: "symfony/event-dispatcher"
      versions: [ "6.x" ]
    - dependency-name: "symfony/http-foundation"
      versions: [ "6.x" ]
    - dependency-name: "symfony/mailer"
      versions: [ "6.x" ]
    - dependency-name: "symfony/process"
      versions: [ "6.x" ]
    - dependency-name: "symfony/routing"
      versions: [ "6.x" ]
    - dependency-name: "symfony/translation"
      versions: [ "6.x" ]

- package-ecosystem: composer
  directory: "/"
  target-branch: stable30
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
    - "dependencies"
    - "stable30"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable29
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
    - "dependencies"
    - "stable29"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable28
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
    - "dependencies"
    - "stable28"
